### PR TITLE
fix button border

### PR DESCRIPTION
**Pull request by simoebenhida**

### CODE REVIEW

**Comment by driesvints** [comment]
Heya. Can you provide a screenshot that shows how this is changed?

**Review by driesvints — CHANGES_REQUESTED** [review]
Heya. Can you provide a screenshot that shows how this is changed?

**Comment by simoebenhida** [comment]
Sure check twitter

**Comment by driesvints** [comment]
Ah I see. The design is actually meant to display it like this but thanks for suggesting :)

**Pull request closed without merging**
